link1: "https://screencasts.railstutorial.org/"
link2: "https://www.railstutorial.org/book"
link3: "https://www.learnenough.com/"
link4: "https://www.learnenough.com/"
link5: "https://rubyonrails.org/"
link6: "https://www.railstutorial.org/"
link7: "https://www.railstutorial.org/contact"
link8: "https://www.railstutorial.org/help"
link9: "https://www.railstutorial.org/book"
link10: "http://news.railstutorial.org"
link11: "https://www.railstutorial.org/"
link12: "http://www.michaelhartl.com/"
link13: "https://www.railstutorial.org/"
link14: "http://rubyonrails.org/"
link15: "rails.png"
size:
  max_name: 50
  max_email: 255
  min_pass: 6
  s_80: 80
  s_50: 50
  s_6: 6
  s_10: 10
session:
  s_1: "1"
timeout_reset_password: 20
